# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\001/',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ndata.proto\"-\n\nRecRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x0f\n\x07movieId\x18\x02 \x01(\x05\"\x1f\n\x0bReqResponse\x12\x10\n\x08movieIds\x18\x01 \x01(\t28\n\x07Greeter\x12-\n\x0eRecommendation\x12\x0b.RecRequest\x1a\x0c.ReqResponse\"\x00\x42\x03Z\x01/b\x06proto3'
)




_RECREQUEST = _descriptor.Descriptor(
  name='RecRequest',
  full_name='RecRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='RecRequest.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='movieId', full_name='RecRequest.movieId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=59,
)


_REQRESPONSE = _descriptor.Descriptor(
  name='ReqResponse',
  full_name='ReqResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='movieIds', full_name='ReqResponse.movieIds', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['RecRequest'] = _RECREQUEST
DESCRIPTOR.message_types_by_name['ReqResponse'] = _REQRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecRequest = _reflection.GeneratedProtocolMessageType('RecRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECREQUEST,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:RecRequest)
  })
_sym_db.RegisterMessage(RecRequest)

ReqResponse = _reflection.GeneratedProtocolMessageType('ReqResponse', (_message.Message,), {
  'DESCRIPTOR' : _REQRESPONSE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:ReqResponse)
  })
_sym_db.RegisterMessage(ReqResponse)


DESCRIPTOR._options = None

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=94,
  serialized_end=150,
  methods=[
  _descriptor.MethodDescriptor(
    name='Recommendation',
    full_name='Greeter.Recommendation',
    index=0,
    containing_service=None,
    input_type=_RECREQUEST,
    output_type=_REQRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
