# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import data_pb2 as data__pb2


class GreeterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CollaborativeRecommendation = channel.unary_unary(
                '/Greeter/CollaborativeRecommendation',
                request_serializer=data__pb2.RecRequest.SerializeToString,
                response_deserializer=data__pb2.ReqResponse.FromString,
                )
        self.ContentBasedRecommendation = channel.unary_unary(
                '/Greeter/ContentBasedRecommendation',
                request_serializer=data__pb2.RecRequest.SerializeToString,
                response_deserializer=data__pb2.ReqResponse.FromString,
                )


class GreeterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CollaborativeRecommendation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ContentBasedRecommendation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CollaborativeRecommendation': grpc.unary_unary_rpc_method_handler(
                    servicer.CollaborativeRecommendation,
                    request_deserializer=data__pb2.RecRequest.FromString,
                    response_serializer=data__pb2.ReqResponse.SerializeToString,
            ),
            'ContentBasedRecommendation': grpc.unary_unary_rpc_method_handler(
                    servicer.ContentBasedRecommendation,
                    request_deserializer=data__pb2.RecRequest.FromString,
                    response_serializer=data__pb2.ReqResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CollaborativeRecommendation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Greeter/CollaborativeRecommendation',
            data__pb2.RecRequest.SerializeToString,
            data__pb2.ReqResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ContentBasedRecommendation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Greeter/ContentBasedRecommendation',
            data__pb2.RecRequest.SerializeToString,
            data__pb2.ReqResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
