# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\001/',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ndata.proto\"<\n\nRecRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x0f\n\x07movieId\x18\x02 \x01(\x05\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\"-\n\x0bReqResponse\x12\x1e\n\x06movies\x18\x01 \x03(\x0b\x32\x0e.MovieResponse\";\n\rMovieResponse\x12\x10\n\x08movie_id\x18\x01 \x01(\x05\x12\x18\n\x10predicted_rating\x18\x02 \x01(\x02\x32\x80\x01\n\x07Greeter\x12:\n\x1b\x43ollaborativeRecommendation\x12\x0b.RecRequest\x1a\x0c.ReqResponse\"\x00\x12\x39\n\x1a\x43ontentBasedRecommendation\x12\x0b.RecRequest\x1a\x0c.ReqResponse\"\x00\x42\x03Z\x01/b\x06proto3'
)




_RECREQUEST = _descriptor.Descriptor(
  name='RecRequest',
  full_name='RecRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='RecRequest.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='movieId', full_name='RecRequest.movieId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='RecRequest.count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=74,
)


_REQRESPONSE = _descriptor.Descriptor(
  name='ReqResponse',
  full_name='ReqResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='movies', full_name='ReqResponse.movies', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=121,
)


_MOVIERESPONSE = _descriptor.Descriptor(
  name='MovieResponse',
  full_name='MovieResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='movie_id', full_name='MovieResponse.movie_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='predicted_rating', full_name='MovieResponse.predicted_rating', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=182,
)

_REQRESPONSE.fields_by_name['movies'].message_type = _MOVIERESPONSE
DESCRIPTOR.message_types_by_name['RecRequest'] = _RECREQUEST
DESCRIPTOR.message_types_by_name['ReqResponse'] = _REQRESPONSE
DESCRIPTOR.message_types_by_name['MovieResponse'] = _MOVIERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecRequest = _reflection.GeneratedProtocolMessageType('RecRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECREQUEST,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:RecRequest)
  })
_sym_db.RegisterMessage(RecRequest)

ReqResponse = _reflection.GeneratedProtocolMessageType('ReqResponse', (_message.Message,), {
  'DESCRIPTOR' : _REQRESPONSE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:ReqResponse)
  })
_sym_db.RegisterMessage(ReqResponse)

MovieResponse = _reflection.GeneratedProtocolMessageType('MovieResponse', (_message.Message,), {
  'DESCRIPTOR' : _MOVIERESPONSE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:MovieResponse)
  })
_sym_db.RegisterMessage(MovieResponse)


DESCRIPTOR._options = None

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=185,
  serialized_end=313,
  methods=[
  _descriptor.MethodDescriptor(
    name='CollaborativeRecommendation',
    full_name='Greeter.CollaborativeRecommendation',
    index=0,
    containing_service=None,
    input_type=_RECREQUEST,
    output_type=_REQRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ContentBasedRecommendation',
    full_name='Greeter.ContentBasedRecommendation',
    index=1,
    containing_service=None,
    input_type=_RECREQUEST,
    output_type=_REQRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
